### ISSUE TITLE
Starter app missing source files

### ISSUE THREAD

**Issue by pomid** [vlcn-io/vite-starter#20]
hello
i cloned this and i found that
Sourcemap for "./node_modules/.pnpm/@vlcn.io+rx-tbl@0.13.0/node_modules/@vlcn.io/rx-tbl/dist/index.js" points to missing source files
Sourcemap for "./node_modules/.pnpm/@vlcn.io+rx-tbl@0.13.0/node_modules/@vlcn.io/rx-tbl/dist/tblrx.js" points to missing source files
Sourcemap for "./node_modules/.pnpm/@vlcn.io+xplat-api@0.13.0/node_modules/@vlcn.io/xplat-api/dist/xplat-api.js" points to missing source files

double checked the packages and can't find whats wrong
cannot add data or drop data in the example app

**Comment by pomid** [comment]
i think rx-tbl and xplat-api have been moved somewhere else 
probably into @vlcn.io/js

**Comment by pomid** [comment]
works fine when built but in dev mode doesn't work !

**Comment by tantaman** [comment]
> works fine when built but in dev mode doesn't work !

The source maps or something else works fine when built but not in dev mode?
