### ISSUE TITLE
pnpm create command fails

### ISSUE THREAD

**Issue by nathanjisaac** [vlcn-io/vite-starter#21]
### How to reproduce:

```shell
docker run --rm --pull always -it node:18 /bin/bash 

npm install -g pnpm
mkdir app && cd app
pnpm create @vlcn.io@latest your-app-name
```

**Error:**

```
ENOENT: no such file or directory, open '/root/.local/share/pnpm/store/v3/tmp/dlx-74/node_modules/create/package.json'
```

**Note**: It does work with `npm create @vlcn.io@latest your-app-name`.

**Comment by nathanjisaac** [comment]
This is my bad. It looks like I need to use a different command. 

```
pnpm create @vlcn.io your-app-name
```

https://www.npmjs.com/package/@vlcn.io/create

I'll see if I can submit a pull request to make this know in the readme.

**Comment by tantaman** [comment]
thanks. Yeah, I think `npm` and `pnpm` have slight variation on `create`?

**Comment by nathanjisaac** [comment]
Yeah, not sure why `pnpm` doesn't like the `@latest` suffix.
